language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ppa:smspillaz/cmake-2.8.12
    packages:
    # install toolchains
    - cmake

os:
  - linux
  - osx
  
    
script:
  - cd TBParser
  - chmod +x install-sh
  - ./install_deps.sh
  - ./configure && make && make install
