language: cpp
compiler:
  - gcc

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    
script:
  - ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  - PARSER_DIR="${ROOT_DIR}/TBParser"
  - ./install_deps.sh
  - ./configure && make && make install
